# Generated by Django 3.2.4 on 2021-10-22 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carrera', models.CharField(max_length=100)),
                ('n_materias_necesarias', models.PositiveSmallIntegerField(default=48)),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_escuela', models.CharField(max_length=100)),
                ('carrera_escuela', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_facu', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InstitucionPropio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.TextField(default='None', max_length=255)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servi', models.CharField(max_length=100)),
                ('descripcion_servi', models.CharField(max_length=200)),
                ('carrera_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_soli', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=50, verbose_name='Estado')),
                ('fecha_realizacion', models.DateField(auto_now_add=True)),
                ('comentario', models.CharField(blank=True, max_length=500)),
                ('carrera_soli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.carrera')),
                ('facultad_soli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.facultad')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.institucionpropio')),
                ('tipo_servi_soli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.tiposervicio')),
            ],
        ),
        migrations.CreateModel(
            name='MaestroPropio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100)),
                ('esta_disponible', models.BooleanField(default=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.carrera')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.escuela')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.facultad')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EncargadoPropio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.facultad')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='facultad_carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.facultad'),
        ),
    ]
