# Generated by Django 3.2.4 on 2021-06-20 17:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carrera', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_escuela', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado_soli', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_facu', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ins', models.CharField(max_length=100)),
                ('email_ins', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('dui', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='nomatch', message='El campo debe tener 10 caracteres y con el formato indicado', regex='^[0-9]{8}-?[0-9]{1}$')])),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=8)),
                ('direccion', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servi', models.CharField(max_length=100)),
                ('descripcion_servi', models.CharField(max_length=200)),
                ('carrera_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizacion', models.DateField(auto_now_add=True)),
                ('comentario', models.CharField(blank=True, max_length=500)),
                ('carrera_soli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.carrera')),
                ('estado_soli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.estadosolicitud')),
                ('facultad_soli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.facultad')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.institucion')),
                ('tipo_servi_soli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.tiposervicio')),
            ],
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100)),
                ('disponibilidad', models.CharField(max_length=20)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.carrera')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.escuela')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.facultad')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.persona')),
            ],
        ),
        migrations.AddField(
            model_name='escuela',
            name='facultad_escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.facultad'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='facultad_carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.facultad'),
        ),
    ]
