# Generated by Django 3.2.4 on 2021-09-26 06:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carrera', models.CharField(max_length=100)),
                ('n_materias_necesarias', models.PositiveSmallIntegerField(default=48)),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_escuela', models.CharField(max_length=100)),
                ('carrera_escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado_soli', models.CharField(default='Pendiente', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_facu', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MiUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Nombre del usuario')),
                ('type', models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('INSTITUCION', 'Institucion'), ('MAESTRO', 'Maestro'), ('ENCARGADO_FACU', 'Encargado_facu'), ('PROYECCION_SOC', 'Proyeccion_soc')], default='ESTUDIANTE', max_length=50, verbose_name='Tipo')),
                ('nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre del usuario')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='direccion de correo')),
                ('telefono', models.CharField(max_length=9, verbose_name='numero de telefono')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='utima sesion')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servi', models.CharField(max_length=100)),
                ('descripcion_servi', models.CharField(max_length=200)),
                ('carrera_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='MaestroPropio',
            fields=[
                ('dui', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='nomatch', message='El campo debe tener 10 caracteres y con el formato indicado', regex='^[0-9]{8}-?[0-9]{1}$')])),
                ('especialidad', models.CharField(max_length=100)),
                ('esta_disponible', models.BooleanField(default=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.carrera')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.escuela')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.facultad')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstitucionPropio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.TextField(default='None', max_length=255)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstudiantePropio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_materias_aprobadas', models.PositiveSmallIntegerField()),
                ('porcentaje_carrera', models.DecimalField(decimal_places=0, max_digits=2)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.carrera')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.facultad')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EncargadoPropio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.facultad')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='facultad_carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.facultad'),
        ),
        migrations.CreateModel(
            name='Encargado_facu',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('SISCOSS.miusuario',),
        ),
        migrations.CreateModel(
            name='Etudiante',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('SISCOSS.miusuario',),
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('SISCOSS.miusuario',),
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('SISCOSS.miusuario',),
        ),
        migrations.CreateModel(
            name='Proyeccion_soc',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('SISCOSS.miusuario',),
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizacion', models.DateField(auto_now_add=True)),
                ('comentario', models.CharField(blank=True, max_length=500)),
                ('carrera_soli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.carrera')),
                ('estado_soli', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.estadosolicitud')),
                ('facultad_soli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.facultad')),
                ('tipo_servi_soli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.tiposervicio')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.institucion')),
            ],
        ),
    ]
