# Generated by Django 3.2.4 on 2021-11-27 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SISCOSS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudiantePropio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.carrera')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.facultad')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='institucionpropio',
            name='nombre_ins',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='ServicioSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_alumno', models.IntegerField()),
                ('cantidad_alumnos', models.IntegerField()),
                ('duracion_horas', models.IntegerField()),
                ('fecha_inicio', models.DateField(auto_now=True)),
                ('fecha_fin', models.DateField()),
                ('estado_servicio', models.CharField(choices=[('NO INICIADO', 'No Iniciado'), ('INICIADO', 'Iniciado'), ('FINALIZADO', 'Finalizado')], default='NO INICIADO', max_length=50, verbose_name='EstadoServicio')),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.estudiantepropio')),
                ('servicio_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.serviciosocial')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroServicioDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_invertidas', models.IntegerField()),
                ('fecha_dia', models.DateField(auto_now=True)),
                ('descripcion_actividad', models.CharField(max_length=255)),
                ('nombre_encargado', models.CharField(max_length=50)),
                ('servicio_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.servicioalumno')),
            ],
        ),
        migrations.CreateModel(
            name='MiniExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materias_aprobadas', models.IntegerField()),
                ('porcentaje_aprobado', models.DecimalField(decimal_places=2, max_digits=4)),
                ('horas_sociales', models.IntegerField()),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.estudiantepropio')),
            ],
        ),
    ]
