# Generated by Django 3.2.4 on 2021-06-22 18:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SISCOSS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestro',
            name='id',
        ),
        migrations.AlterField(
            model_name='maestro',
            name='dui',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='nomatch', message='El campo debe tener 10 caracteres y con el formato indicado', regex='^[0-9]{8}-?[0-9]{1}$')]),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado_soli',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SISCOSS.estadosolicitud'),
        ),
    ]
