# Generated by Django 3.2.4 on 2021-11-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISCOSS', '0002_auto_20211127_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciosocial',
            name='fecha_fin',
            field=models.DateField(null=True),
        ),
    ]
