# Generated by Django 3.2.4 on 2021-10-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Nombre del usuario')),
                ('type', models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('INSTITUCION', 'Institucion'), ('MAESTRO', 'Maestro'), ('ENCARGADO_FACU', 'Encargado de la Facultad'), ('PROYECCION_SOC', 'Proyeccion Social')], default='ESTUDIANTE', max_length=50, verbose_name='Tipo')),
                ('nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre del usuario')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='direccion de correo')),
                ('telefono', models.CharField(max_length=9, verbose_name='numero de telefono')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='utima sesion')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Encargado_facu',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('CustomUsers.miusuario',),
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('CustomUsers.miusuario',),
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('CustomUsers.miusuario',),
        ),
        migrations.CreateModel(
            name='Proyeccion_soc',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('CustomUsers.miusuario',),
        ),
    ]
